"""empty message

Revision ID: 22be0c7e1f23
Revises: 835b02823316
Create Date: 2024-08-19 03:47:19.491841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22be0c7e1f23'
down_revision = '835b02823316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_messge_embedding', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parter', schema=None) as batch_op:
        batch_op.drop_column('partner_messge_embedding')

    # ### end Alembic commands ###
