"""empty message

Revision ID: 80f130f87f20
Revises: ab639514f8ab
Create Date: 2024-08-19 03:12:39.915927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f130f87f20'
down_revision = 'ab639514f8ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('partner_past_message', sa.String(length=4000), nullable=True))
        batch_op.add_column(sa.Column('partner_email', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_partner_email'), ['partner_email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_user_name'), ['user_name'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_user_user_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_partner_email'), type_='unique')
        batch_op.drop_column('partner_email')
        batch_op.drop_column('partner_past_message')
        batch_op.drop_column('partner')

    # ### end Alembic commands ###
