"""empty message

Revision ID: 835b02823316
Revises: 80f130f87f20
Create Date: 2024-08-19 03:43:05.973520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835b02823316'
down_revision = '80f130f87f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parter',
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('partner_name', sa.String(length=20), nullable=True),
    sa.Column('partner_past_message', sa.String(length=4000), nullable=True),
    sa.Column('partner_email', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_parter_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partner_id', name=op.f('pk_parter')),
    sa.UniqueConstraint('partner_email', name=op.f('uq_parter_partner_email'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_partner_email', type_='unique')
        batch_op.drop_column('partner_past_message')
        batch_op.drop_column('partner_email')
        batch_op.drop_column('partner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('partner_email', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('partner_past_message', sa.VARCHAR(length=4000), nullable=True))
        batch_op.create_unique_constraint('uq_user_partner_email', ['partner_email'])

    op.drop_table('parter')
    # ### end Alembic commands ###
