"""empty message

Revision ID: a6544d391dc6
Revises: 22be0c7e1f23
Create Date: 2024-08-19 16:18:19.759449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6544d391dc6'
down_revision = '22be0c7e1f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fishing_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=4000), nullable=True))
        batch_op.drop_column('messge')

    with op.batch_alter_table('parter', schema=None) as batch_op:
        batch_op.alter_column('partner_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('partner_email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parter', schema=None) as batch_op:
        batch_op.alter_column('partner_email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('partner_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('fishing_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messge', sa.VARCHAR(length=4000), nullable=True))
        batch_op.drop_column('message')

    # ### end Alembic commands ###
