"""empty message

Revision ID: ab639514f8ab
Revises: 
Create Date: 2024-08-19 00:52:36.752715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab639514f8ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fishing_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('messge', sa.String(length=4000), nullable=True),
    sa.Column('messge_embedding', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('fishing_messages')
    # ### end Alembic commands ###
